# fly.toml app configuration file generated for pax-habit-helper on 2024-02-07T10:28:59-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pax-habit-helper"
primary_region = "bos"

[mounts]
  source="results"
  destination="/results"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]